FROM centos:7

# https://www.linuxprobe.com/centos-rsyslogloganalyzer-mysql.html
# https://www.cnblogs.com/mchina/p/linux-centos-rsyslog-loganalyzer-mysql-log-server.html
# https://blog.csdn.net/qq_37187976/article/details/79231854
# https://www.cnblogs.com/Eivll0m/p/6700828.html

